apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - service.yaml
  - statefulset.yaml
  - envoy-filter.yaml
  - pvc.yaml

namespace: istio-system

configMapGenerator:
  - name: oidc-authservice-parameters
    envs:
      - params.env

secretGenerator:
  - name: oidc-authservice-client
    type: Opaque
    envs:
      - secret_params.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: gcr.io/arrikto/kubeflow/oidc-authservice
    newName: docker.io/kubeflowmanifestswg/oidc-authservice
    newTag: e236439
