vars:
  - file: config/common-defaults.yaml
  - file: config/auth-defaults.yaml
  - file: config/users-defaults.yaml
  - file: "{{ args.config }}"
    when: args.config

deployments:
  - path: namespaces
  - barrier: true
  - include: common
  - barrier: true
  - include: apps
  - include: contrib
  - barrier: true
  - include: users
