apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-eventing
resources:
- upstream/eventing-core.yaml
{% if common.knative.eventing.inMemoryChannelsEnabled %}
- upstream/in-memory-channel.yaml
{% endif %}
{% if common.knative.eventing.mtChannelBrokerEnabled %}
- upstream/mt-channel-broker.yaml
{% endif %}

patchesStrategicMerge:
- patches/clusterrole-patch.yaml
commonLabels:
  kustomize.component: knative
  app.kubernetes.io/component: knative-eventing
  app.kubernetes.io/name: knative-eventing
