apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: m2m-token-issuer
  namespace: istio-system
spec:
  jwtRules:
    - forwardOriginalToken: true
      issuer: {{ common.oidc_client.oauth2_proxy.m2m.tokenIssuer }}
      outputClaimToHeaders:
        - claim: sub
          header: x-auth-request-user
        - claim: sub
          header: kubeflow-userid
