common:
  cert_manager:
    enabled: true

  istio:
    cni:
      enabled: false
    clusterLocalGateway:
      enabled: false

  knative:
    serving:
      useIstioGateway: true
    eventing:
      enabled: true
      inMemoryChannelsEnabled: false
      mtChannelBrokerEnabled: false
