common:
  cert_manager:
    enabled: true

  istio:
    cni:
      enabled: false
    clusterLocalGateway:
      enabled: false

  oidc_client:
    auth_service:
      enabled: true
    oauth2_proxy:
      enabled: false
      cloudFlare: false
      m2m:
        enabled: true
        selfSigned: true
        # replace this with a real one in case selfSigned=false, e.g. https://oidc.eks.region.amazonaws.com/id/1234abcd
        tokenIssuer: https://kubernetes.default.svc.cluster.local

  dex:
    staticPasswords:
      - email: "user@example.com"
        hash: "$2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72"
        username: "user"
        userID: "15841185641784"
    oidc:
      clientID: kubeflow-oidc-authservice
      clientSecret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
