{% if not auth.dex.staticPasswords %}
  {{ raise("you must provide a list of static passwords via auth.dex.staticPassword") }}
{% endif %}

config:
  issuer: http://dex.auth.svc.cluster.local:5556/dex
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: 0.0.0.0:5556
  logger:
    level: "debug"
    format: text
  oauth2:
    skipApprovalScreen: true
  {% if auth.dex.staticPasswords %}
  enablePasswordDB: true
  staticPasswords: {{ auth.dex.staticPasswords | to_json }}
  {% endif %}
  staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs:
        {% if auth.auth_service.enabled %}
        - "/authservice/oidc/callback"
        {% endif %}
        {% if auth.oauth2_proxy.enabled %}
        - "/oauth2/callback"
        {% endif %}
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET

envFrom:
  - secretRef:
      name: dex-oidc-client
