apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
  - helm-rendered.yaml
  - virtual-service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: dex-oidc-client
    type: Opaque
    envs:
      - secret_params.env
