apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
{% if auth.oauth2_proxy.cloudFlare %}
- authorizationpolicy.istio-ingressgateway-oauth2-proxy-cloudflare.yaml
{% else %}
- authorizationpolicy.istio-ingressgateway-oauth2-proxy.yaml
{% endif %}
- requestauthentication.dex-jwt.yaml
