namespace: istio-system

resources:
  - helm-rendered.yaml
  - gateway_authorizationpolicy.yaml
  - deny_all_authorizationpolicy.yaml
  - gateway.yaml
  - x-forwarded-host.yaml

patches:
  - path: patches/istio-configmap-disable-tracing.yaml
  - path: patches/disable-debugging.yaml
  - path: patches/istiod-remove-pdb.yaml
