deployments:
  - include: cert-manager
  - barrier: true
  - include: istio
  - include: oidc-client
  - path: dex
  - include: knative
  - barrier: true
  - path: kubeflow-roles
  - path: kubeflow-istio-resources
