apiVersion: batch/v1
kind: Job
metadata:
  name: configure-oidc-issuer-jwks-in-requestauthentication
  namespace: istio-system
  annotations:
    kluctl.io/hook-weight: 100
    kluctl.io/hook-wait: "false"
spec:
  template:
    metadata:
      labels: {}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: self-signed-oidc-issuer-configurator
      containers:
        - image: curlimages/curl
          name: configure-oidc-issuer-jwks-in-requestauthentication
          command:
            - /script.sh
          envFrom:
            - configMapRef:
                name: configure-self-signed-oidc-issuer-envs
          volumeMounts:
            - mountPath: /script.sh
              name: script
              subPath: script.sh
          resources: {}
      volumes:
        - name: script
          configMap:
            name: configure-self-signed-oidc-issuer-script
            defaultMode: 0777
            items:
              - key: script.sh
                path: script.sh
